name: HotBlock
main: surva\hotblock\HotBlock
version: 1.1.7
api: 4.0.0

softdepend: ["EconomyAPI", "Capital", "InfoAPI"]

author: survanetwork
description: A funny PvP minigame
website: https://plugins.surva.net/#hotblock
