name: HotBlock
main: surva\hotblock\HotBlock
version: 1.1.5
api: 4.0.0

softdepend: ["EconomyAPI"]

author: survanetwork
description: A funny PvP minigame
website: https://plugins.surva.net/#hotblock
